from PyQt6.QtWidgets import QWidget, QVBoxLayout, QLabel, QListWidget, QPushButton, QHBoxLayout, QScrollArea

class ExclusionTab(QWidget):
    def __init__(self, parent=None):
        super().__init__(parent)
        scroll = QScrollArea(self)
        scroll.setWidgetResizable(True)
        content = QWidget()
        layout = QVBoxLayout()
        excl_label = QLabel("Exclusion Layers:")
        layout.addWidget(excl_label)
        self.excl_list_widget = QListWidget()
        layout.addWidget(self.excl_list_widget)
        excl_add_btn = QPushButton("Add exclusion...")
        excl_add_btn.setObjectName("add_exclusion_btn")
        excl_remove_btn = QPushButton("Remove selected")
        excl_remove_btn.setObjectName("remove_exclusion_btn")
        excl_btns_layout = QHBoxLayout()
        excl_btns_layout.addWidget(excl_add_btn)
        excl_btns_layout.addWidget(excl_remove_btn)
        layout.addLayout(excl_btns_layout)
        content.setLayout(layout)
        scroll.setWidget(content)
        main_layout = QVBoxLayout()
        main_layout.addWidget(scroll)
        self.setLayout(main_layout) 