from PyQt6.QtWidgets import QWidget, QVBoxLayout, QFormLayout, QLineEdit, QPushButton, QComboBox, QSpinBox, QDoubleSpinBox, QHBoxLayout, QProgressBar, QScrollArea
from PyQt6.QtCore import pyqtSignal

class PipelineTab(QWidget):
    def __init__(self, parent=None):
        super().__init__(parent)
        scroll = QScrollArea(self)
        scroll.setWidgetResizable(True)
        content = QWidget()
        layout = QVBoxLayout()
        self.input_line = QLineEdit()
        self.input_browse_btn = QPushButton("Browse...")
        input_layout = QHBoxLayout()
        input_layout.addWidget(self.input_line)
        input_layout.addWidget(self.input_browse_btn)
        self.output_line = QLineEdit()
        self.output_browse_btn = QPushButton("Browse...")
        output_layout = QHBoxLayout()
        output_layout.addWidget(self.output_line)
        output_layout.addWidget(self.output_browse_btn)
        self.style_combo = QComboBox()
        self.style_combo.addItems(["calibration", "control", "custom"])
        form_layout = QFormLayout()
        form_layout.addRow("Input file:", input_layout)
        form_layout.addRow("Output directory:", output_layout)
        form_layout.addRow("Processing style:", self.style_combo)
        self.intensity_spin = QSpinBox()
        self.intensity_spin.setRange(1, 1000)
        self.intensity_spin.setValue(50)
        form_layout.addRow("Intensity (ha per parcel):", self.intensity_spin)
        self.min_parcels_spin = QSpinBox()
        self.min_parcels_spin.setRange(1, 100)
        self.min_parcels_spin.setValue(1)
        form_layout.addRow("Min parcels per group:", self.min_parcels_spin)
        self.max_parcels_spin = QSpinBox()
        self.max_parcels_spin.setRange(1, 100)
        self.max_parcels_spin.setValue(10)
        form_layout.addRow("Max parcels per group:", self.max_parcels_spin)
        self.min_area_spin = QDoubleSpinBox()
        self.min_area_spin.setRange(0.01, 100.0)
        self.min_area_spin.setSingleStep(0.01)
        self.min_area_spin.setValue(0.3)
        form_layout.addRow("Min area (ha):", self.min_area_spin)
        self.buffer_spin = QSpinBox()
        self.buffer_spin.setRange(-1000, 1000)
        self.buffer_spin.setValue(-20)
        form_layout.addRow("Buffer distance (m):", self.buffer_spin)
        self.min_distance_spin = QDoubleSpinBox()
        self.min_distance_spin.setRange(0.0, 1000.0)
        self.min_distance_spin.setSingleStep(0.1)
        self.min_distance_spin.setValue(60.0)
        form_layout.addRow("Min distance between parcels (m):", self.min_distance_spin)
        layout.addLayout(form_layout)
        self.run_btn = QPushButton("Run")
        self.stop_btn = QPushButton("Stop")
        self.stop_btn.setEnabled(False)
        run_stop_layout = QHBoxLayout()
        run_stop_layout.addWidget(self.run_btn)
        run_stop_layout.addWidget(self.stop_btn)
        layout.addLayout(run_stop_layout)
        self.progress_bar = QProgressBar()
        self.progress_bar.setValue(0)
        layout.addWidget(self.progress_bar)
        content.setLayout(layout)
        scroll.setWidget(content)
        main_layout = QVBoxLayout()
        main_layout.addWidget(scroll)
        self.setLayout(main_layout) 